[package]
name = "thInk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vello = "0.2.1"
winit = "0.30.5"
anyhow = "1.0.89"
pollster = "0.3.0"
nalgebra = "0.33.0"
rand = "0.8.5"
rayon = "1.5.1"